# Generated by Django 2.1.4 on 2019-03-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='faculty',
            field=models.CharField(default='Bsc', max_length=75),
        ),
    ]
