# Generated by Django 2.1.4 on 2019-04-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_questions_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='year',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='questions',
            name='faculty',
            field=models.CharField(max_length=75),
        ),
    ]
