# Generated by Django 2.1.4 on 2019-04-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20190404_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='year',
            field=models.IntegerField(),
        ),
    ]
