# Generated by Django 2.1.4 on 2019-04-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20190404_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='subject',
            field=models.CharField(default='Science', max_length=100),
        ),
        migrations.AlterField(
            model_name='questions',
            name='semester',
            field=models.IntegerField(),
        ),
    ]
