# Generated by Django 2.1.4 on 2019-04-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20190404_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
