# Generated by Django 2.1 on 2019-04-11 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20190411_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionfiles',
            old_name='sname',
            new_name='sName',
        ),
    ]
